name: Frontend CI

on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: student-management-client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@4.13.0 --activate

      - name: Verify Yarn version
        run: yarn -v

      - name: Cache Yarn
        uses: actions/cache@v4
        with:
          path: student-management-client/.yarn/cache
          key: yarn-${{ runner.os }}-${{ hashFiles('student-management-client/yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run ESLint
        run: yarn lint

      - name: Build Next.js app
        run: yarn build